# Generated by Django 4.2.4 on 2023-08-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacturacionNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio_mxn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.TextField(blank=True)),
            ],
        ),
    ]
