# Generated by Django 4.2.4 on 2023-08-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_nomina', '0002_detallesfactura_alter_facturacionnomina_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesfactura',
            name='fecha_tabla',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallesfactura',
            name='all',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='detallesfactura',
            name='nomina',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detallesfactura',
            name='pdd',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detallesfactura',
            name='pue',
            field=models.IntegerField(),
        ),
    ]
