# Generated by Django 4.2.2 on 2023-08-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_nomina', '0003_detallesfactura_fecha_tabla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesfactura',
            name='ejemplo',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
